# Generated by Django 5.1.5 on 2025-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_status_alter_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('W', 'В ожидании'), ('D', 'Готово'), ('P', 'Оплачено')], default='W'),
        ),
    ]
